ActiveRecord::Base.transaction do
  puts "Loading Books to App DB started..."
  pj = Project.find(2) 
  puts "Project #{pj.name} starting"
  
  bookn = Book.create(name: 'נכסים', kind: 'מ', project_id: pj.id)
  puts "Did the first #{bookn.id} - #{bookn.name}"
  bookn = Book.create(name: 'ח-ן בנק', kind: 'מ', group_id: 1, project_id: pj.id)
  puts "Did the second"
  bookn = Book.create(name: 'חובות דיירים', kind: 'מ', group_id: 1, project_id: pj.id)
  bookn = Book.create(name: 'קופה קטנה', kind: 'מ', group_id: 1, project_id: pj.id)
  bookn = Book.create(name: 'רכוש קבוע', kind: 'מ', group_id: 1, project_id: pj.id)
  bookn = Book.create(name: 'דיירים', kind: 'מ', group_id: 1, project_id: pj.id)
  bookn = Book.create(name: 'התחייבויות', kind: 'מ', project_id: pj.id)
  bookn = Book.create(name: 'ספקים', kind: 'מ', group_id: 7, project_id: pj.id)
  bookn = Book.create(name: 'שיקים שניתנו', kind: 'מ', group_id: 7, project_id: pj.id)
  bookn = Book.create(name: 'תקבולים לעתיד', kind: 'מ', group_id: 7, project_id: pj.id)
  bookn = Book.create(name: 'תקציב', kind: 'מ', group_id: 7, project_id: pj.id)
  bookn = Book.create(name: 'הכנסות', kind: 'ת', project_id: pj.id)
  bookn = Book.create(name: 'מיסי וועד חודשיים', kind: 'ת', group_id: 12, project_id: pj.id)
  bookn = Book.create(name: 'הכנסות אחרות', kind: 'ת', group_id: 12, project_id: pj.id)
  bookn = Book.create(name: 'הוצאות', kind: 'ת', project_id: pj.id)
  bookn = Book.create(name: 'כח אדם', kind: 'ת', group_id: 15, project_id: pj.id)
  bookn = Book.create(name: 'אב הבית', kind: 'ת', group_id: 16, project_id: pj.id)
  bookn = Book.create(name: 'הפרשות סוציאליות - בטל"א', kind: 'ת', group_id: 16, project_id: pj.id)
  bookn = Book.create(name: 'משכורות - מס מעבידים', kind: 'ת', group_id: 16, project_id: pj.id)
  bookn = Book.create(name: 'הפרשות סוציאליות - פנסיה', kind: 'ת', group_id: 16, project_id: pj.id)
  bookn = Book.create(name: 'מפעיל בריכה', kind: 'ת', group_id: 16, project_id: pj.id)
  bookn = Book.create(name: 'מציל', kind: 'ת', group_id: 16, project_id: pj.id)
  bookn = Book.create(name: 'נקיון', kind: 'ת', group_id: 16, project_id: pj.id)
  bookn = Book.create(name: 'פקידי קבלה', kind: 'ת', group_id: 16, project_id: pj.id)
  bookn = Book.create(name: 'תחזוקה וציוד', kind: 'ת', group_id: 15, project_id: pj.id)
  bookn = Book.create(name: 'בדיקת מעליות', kind: 'ת', group_id: 25, project_id: pj.id)
  bookn = Book.create(name: 'גילוי אש', kind: 'ת', group_id: 25, project_id: pj.id)
  bookn = Book.create(name: 'גנרטור', kind: 'ת', group_id: 25, project_id: pj.id)
  bookn = Book.create(name: 'גנרטור- סולר', kind: 'ת', group_id: 25, project_id: pj.id)
  bookn = Book.create(name: 'דחסן אשפה', kind: 'ת', group_id: 25, project_id: pj.id)
  bookn = Book.create(name: 'כיבוי אש', kind: 'ת', group_id: 25, project_id: pj.id)
  bookn = Book.create(name: 'מאגרי מים', kind: 'ת', group_id: 25, project_id: pj.id)
  bookn = Book.create(name: 'מיזוג אוויר', kind: 'ת', group_id: 25, project_id: pj.id)
  bookn = Book.create(name: 'מעליות', kind: 'ת', group_id: 25, project_id: pj.id)
  bookn = Book.create(name: 'מערכות מים', kind: 'ת', group_id: 25, project_id: pj.id)
  bookn = Book.create(name: 'מפוחים ו-CO', kind: 'ת', group_id: 25, project_id: pj.id)
  bookn = Book.create(name: 'עבודות חשמל', kind: 'ת', group_id: 25, project_id: pj.id)
  bookn = Book.create(name: 'שליטה בעשן', kind: 'ת', group_id: 25, project_id: pj.id)
  bookn = Book.create(name: 'בדיקת תקן שנתית', kind: 'ת', group_id: 25, project_id: pj.id)
  bookn = Book.create(name: 'בריכה וחדר כושר', kind: 'ת', group_id: 15, project_id: pj.id)
  bookn = Book.create(name: 'בדיקת מים', kind: 'ת', group_id: 40, project_id: pj.id)
  bookn = Book.create(name: 'כימיקלים', kind: 'ת', group_id: 40, project_id: pj.id)
  bookn = Book.create(name: 'הוצאות שוטפות', kind: 'ת', group_id: 15, project_id: pj.id)
  bookn = Book.create(name: 'בצ"מ, פיתוח וחיסכון', kind: 'ת', group_id: 43, project_id: pj.id)
  bookn = Book.create(name: 'גינון', kind: 'ת', group_id: 43, project_id: pj.id)
  bookn = Book.create(name: 'חומרי ניקוי', kind: 'ת', group_id: 43, project_id: pj.id)
  bookn = Book.create(name: 'נטרול ריחות', kind: 'ת', group_id: 43, project_id: pj.id)
  bookn = Book.create(name: 'ניקוי החניון', kind: 'ת', group_id: 43, project_id: pj.id)
  bookn = Book.create(name: 'תחזוקה', kind: 'ת', group_id: 43, project_id: pj.id)
  bookn = Book.create(name: 'ביטוחים', kind: 'ת', group_id: 15, project_id: pj.id)
  bookn = Book.create(name: 'שירותים שוטפים', kind: 'ת', group_id: 15, project_id: pj.id)
  bookn = Book.create(name: 'אינטרנט', kind: 'ת', group_id: 51, project_id: pj.id)
  bookn = Book.create(name: 'חשמל', kind: 'ת', group_id: 51, project_id: pj.id)
  bookn = Book.create(name: 'טלפון', kind: 'ת', group_id: 51, project_id: pj.id)
  bookn = Book.create(name: 'כבלים', kind: 'ת', group_id: 51, project_id: pj.id)
  bookn = Book.create(name: 'עמלות בנקים', kind: 'ת', group_id: 51, project_id: pj.id)
  bookn = Book.create(name: 'ניהול', kind: 'ת', group_id: 15, project_id: pj.id)
  bookn = Book.create(name: 'קרן שימור', kind: 'ת', group_id: 15, project_id: pj.id)
  bookn = Book.create(name: 'עזר', kind: 'מ', project_id: pj.id)
  bookn = Book.create(name: 'בטוח לאומי', kind: 'מ', group_id: 59, project_id: pj.id)
  bookn = Book.create(name: 'הזמנות', kind: 'מ', group_id: 59, project_id: pj.id)
  bookn = Book.create(name: 'הפרשות לספקים', kind: 'מ', group_id: 59, project_id: pj.id)
  bookn = Book.create(name: 'זיכוי דיירים', kind: 'מ', group_id: 59, project_id: pj.id)
  bookn = Book.create(name: 'משכורות - לשלם', kind: 'מ', group_id: 59, project_id: pj.id)
  bookn = Book.create(name: 'סוף שנה', kind: 'מ', group_id: 59, project_id: pj.id)
  bookn = Book.create(name: 'שיקים', kind: 'מ', group_id: 59, project_id: pj.id)
  
  puts "...Loading Ended"
end